language: objective-c
osx_image: xcode10.2
xcode_workspace: ShopifyiOSSDKTest/ShopifyiOSSDKTest.xcworkspace
xcode_scheme: ShopifyiOSSDKTest
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 8
podfile: ShopifyiOSSDKTest/Podfile
cache: cocoapods

before_install:
  - pod repo update
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - cd ShopifyiOSSDKTest
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

cache:
  directories:
  - ShopifyiOSSDKTest/Carthage
