source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!

def common_pods
  pod "Mobile-Buy-SDK"
  pod 'SVProgressHUD'
end

target 'ShopifyiOSSDKTest' do
  common_pods
end

target 'ShopifyiOSSDKTestTests' do
  common_pods
end
