source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!

target 'ShopifyiOSSDKTest' do
  pod "Mobile-Buy-SDK"
  #pod "FunctionalTableData"
  pod 'SVProgressHUD'

  target 'ShopifyiOSSDKTestTests' do
    inherit! :search_paths
  end

end
