# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ShopifyiOSSDKTest' do
use_frameworks!

pod "Mobile-Buy-SDK"
pod "Apollo"

pod 'SVProgressHUD'

end
